Pokemon tools
lujeremy/JerBot pull request #4
Opened 2019-08-04 21:00 UTC by lujeremy

- Added new commands
  - !pokemon: shows the type and image of a random pokemon, or a specified one
  - !nature: shows the list of all natures, or when one is specified, how it affects a pokemon's stat growth
- Updated Unirest
- Removed some unnecessary default constructors that would otherwise be implied

2019-08-04 22:07 UTC, vincentzhang96 requested changes

2019-08-04 22:07 UTC, vincentzhang96 commented on src/main/java/io/jlu/alfredo/commands/NatureCommand.java
> +        if (contentRaw.length() < "nature ".length() + 2) {
Move the contents of this if to another function

2019-08-04 22:07 UTC, vincentzhang96 commented on src/main/java/io/jlu/alfredo/commands/NatureCommand.java
> +
Move the remainder of this function to its own function

2019-08-04 22:07 UTC, vincentzhang96 commented on src/main/java/io/jlu/alfredo/commands/PokemonCommand.java
> +    private final Logger logger = Logger.getLogger(this.getClass().getName());
ditto

2019-08-04 22:07 UTC, vincentzhang96 commented on src/main/java/io/jlu/alfredo/commands/PokemonCommand.java
> +            mainType = AlfredoUtils.capitalizeFirst(jsonObject.getJSONArray("types").getJSONObject(0).getJSONObject("type").getString("name"));
insert newlines e.g.
```
mainType = AlfredoUtils.capitalizeFirst(
    jsonObject.getJSONArray("types")
        .getJSONObject(0)
        .getJSONObect("type")
...
```

2019-08-04 22:07 UTC, vincentzhang96 commented on src/main/java/io/jlu/alfredo/commands/PokemonCommand.java
> +        if (jsonObject.getJSONArray("types").length() == 1) {
Factor out `jsonObject.getJSONArray("types")` into its own variable and reuse it

2019-08-04 22:07 UTC, vincentzhang96 commented on src/main/java/io/jlu/alfredo/utils/AlfredoUtils.java
> +        // TODO: How safe is this...?
Pretty OK

2019-08-04 22:15 UTC, vincentzhang96 commented on src/main/java/io/jlu/alfredo/utils/AlfredoUtils.java
> +        pokemonTypeColors.put("normal", "#A8A878");
Insert the color directly instead

2019-08-16 23:16 UTC, vincentzhang96 commented on src/main/java/io/jlu/alfredo/Alfredo.java
> +    private final Logger LOG = LoggerFactory.getLogger(MethodHandles.lookup().lookupClass());
Nit: Normally named `LOGGER`

2019-08-16 23:18 UTC, vincentzhang96 commented on src/main/java/io/jlu/alfredo/commands/NatureCommand.java
> +        MessageEmbed embed = natureCache.get("");
Prefer caching the data not the representation, e.g. cache the API response rather than what you make of it

2019-08-16 23:19 UTC, vincentzhang96 approved these changes

2019-08-18 19:57 UTC, merged

2023-04-25 00:21 UTC, lujeremy commented on src/main/java/io/jlu/alfredo/commands/NatureCommand.java
> +    private final Logger logger = Logger.getLogger(this.getClass().getName());
Recommend `private static final Logger LOGGER = ...`